blog/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('blog-list', BlogListView.as_view(), name='blog_list_page'),
    path('blog-grid', BlogGridView.as_view(), name='blog_grid_page'),
    path('blog-detail/<str:slug>/', BlogDetailView.as_view(), name='blog_detail'),
]

mainproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)
from .views import IndexView, SubscribeView
from .oauth import FacebookLogin, GoogleLogin
from user.api.urls import MyTokenObtainPairView


schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="batuwa@email.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('main/', admin.site.urls),

    #  path('', RedirectView.as_view(pattern_name='dashboard'),name='redirect'),
    #  path('', RedirectView.as_view(pattern_name='dashboard'),name='redirect'),
    path('', IndexView.as_view(), name='index'),
    path('dashboard/', RedirectView.as_view(pattern_name='dashboard'), name='redirect'),
    path('user/', include('user.urls')),
    path('project/', include('projects.urls')),
    path('membership/', include('membership.urls')),
    path('site/', include('sitesettings.urls')),
    path('admin/', include('user.admin_urls')),
    path('notice/', include('notification.urls')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls')),
    path('payments/', include('payments.urls')),
    path('blog/', include('blog.urls')),
    path('subscribe', SubscribeView.as_view(), name='subscribe'),

    # path('jwt/create/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('jwt/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('jwt/verify/', TokenVerifyView.as_view(), name='token_verify'),


    path('api/projects/', include('projects.api.urls')),
    path('api/user/', include('user.api.urls')),
    path('api/payments/', include('payments.api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="user/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('oauth/facebook/', FacebookLogin.as_view(), name='facebook_oauth'),
    path('oauth/google/', GoogleLogin.as_view(), name='google_oauth'),
    # path('dj-rest-auth/', include('dj_rest_auth.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns += [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger',
                                               cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc',
                                             cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/api/urls.py
from django.urls import path,include
from .views import *
from rest_framework.routers import DefaultRouter
from .admin_view import *

router = DefaultRouter()
router.register(r'projects', ProjectViewSet, basename='projects')
router.register(r'categories', CategoryViewset, basename='categories')
router.register(r'invites', InviteViewSet, basename='invites')



urlpatterns = [
    path('',include(router.urls)),
    path('all_reviews/', GetAllReviews.as_view()),
    path('create_review/', CreateReview.as_view()),
    path('reviews_got_by_me/', ReviewGotApi.as_view()),
    path('project-info/', OverallProjectInfo.as_view()),
    path('reviews_given_by_me/', ReviewGivenApi.as_view()),
    path('answer-invite/', AnswerInviteAPI.as_view(),name="answer_invite_api"),
    path('check-my-availability/', CheckMyAvailability.as_view(),name="check_my_availability_api"),
    path('change-status/<int:id>/',ChangeProjectStatus.as_view(), name='change_status'),
    path('approve-project/<int:project_id>/', ApproveProject.as_view(),name="approve_project"),
    path('review-detail/<int:id>/', ReviewDetailApi.as_view(),name="review_api_detail"),
]


admin_urls = [
    path('answer-identity-request/', AnswerIdentiyRequest.as_view(),name="answer_identity_request"),
]

urlpatterns+=admin_urls

projects/urls.py
from django.urls import path, include
from .views import *
from .freelancer_views import *
# app_name = 'projects'

employer_urls = [
      path('create-project/', CreateProject.as_view(), name='create_project'),
      path('edit-project/<int:id>/',EditProject.as_view(), name='edit_project'),
      path('add-review/<int:id>/',AddReviewForProject.as_view(), name='add_review'),
      path('projects/<str:project_type>/',AllProjects.as_view(), name='all_projects'),
      path('invite-user/',CreateInvite.as_view(), name='invite_user'),
      path('project/<int:id>/',ProjectDetail.as_view(), name='project_detail'),
      path('pending-projects/',PendingProjects.as_view(), name='pending_projects'),
      path('ongoing-projects/',OngoingProjects.as_view(), name='ongoing_projects'),
      path('completed-projects/',CompletedProjects.as_view(), name='completed_projects'),
      path('cancelled-projects/',CancelledProjects.as_view(), name='cancelled_projects'),
      #path('project-chat/<str:user1>/<str:user2>/',ProjectChatView.as_view(), name='project_chat'),
]

freelancer_urls =[
      path('find-projects/',FindProject.as_view(), name='find_projects'),
      path('project-proposal/',ProjectProposal.as_view(), name='proposals'),
      path('my-ongoing-projects/',FreeOngoingProject.as_view(), name='free_ongoing_projects'),
      path('my-completed-projects/',FreeCompletedProject.as_view(), name='free_completed_projects'),
      path('my-canceleed-projects/',FreeCancelledProject.as_view(), name='free_cancelled_projects'),
      path('invite-list/',FreeInviteList.as_view(), name='free_invite_list'),
      path('projects-detail/v/<int:id>/',FreeProjectDetail.as_view(), name='free_project_detail'),
      path('favourite-project/',FavouriteProjectView.as_view(), name='fav_project_view'),
      path('favourite-project/<int:id>/',FavoriteProject.as_view(), name='fav_project'),
      path('remove-fav/<int:id>/',remove_favourite, name='remove_fav_project'),
      path('delete-proposal/<int:id>/',delete_proposal, name='delete_proposal'),
      path('search-all/',FindProjectAndFreelancerView.as_view(), name='find_all'),
]

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'skills', FeeViewset, basename='skills')

urlpatterns_admin = [
      path('skills-list/',SkillPage.as_view() , name="skills_list"),
      path('',include(router.urls)),

      path('review-approve/<int:id>/',ReviewApprove.as_view() , name="review_approve"),
      path('review-trash/<int:id>/',ReviewTrash.as_view() , name="review_trash"),
]
urlpatterns=employer_urls+freelancer_urls+urlpatterns_admin

projects/models.py
from django.db import models
from django.utils.functional import cached_property
from django_countries.fields import CountryField
from datetime import date
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse
from notification.models import Notification
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class Portfolio(models.Model):
    user = models.ForeignKey(
        "user.User", related_name="portfolios", on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    detail = models.TextField(null=True, blank=True)
    link = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.title


class PortfolioFile(models.Model):
    portfolio_of = models.ForeignKey(Portfolio,  on_delete=models.CASCADE)
    files = models.FileField(upload_to='portfolio_files')

    @cached_property
    def get_file_name(self):
        return self.files.url.split("/")[-1]


class ProjectCategory(models.Model):
    name = models.CharField(max_length=50)
    created_on = models.DateField(auto_now_add=True, null=True)

    def __str__(self) -> str:
        return self.name


class DesiredExpertise(models.Model):
    skill_name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.skill_name


class ProjectManager(models.Manager):
    def available(self):
        return Project.objects.filter(can_apply=True, expires_on__gte=date.today())


class Project(models.Model):
    pricing_types = [
        ("F", "Fixed Budget Price"),
        ("H", "Hourly Pricing"),
        ("B", "Biding Price"),
    ]
    pricing_types = [
        ("F", "Fixed Budget Price"),
        ("H", "Hourly Pricing"),
        ("B", "Biding Price"),
    ]

    project_status = [
        ("PEN", "Pending"),
        # approved by admin/ freelancer can only bid or apply in this status
        ("Active", "Active"),
        ("ON", "Ongoing"),
        ("COM", "Completed"),
        ("CAN", "Cancelled"),
    ]

    price_stats = [
        ("FIXED", "FIXED"),
        ("NEGOTIATE", "Can Negotiate"),
    ]

    deposit_status = [
        ("Unpaid", "Unpaid"),
        ("Paid", "Paid"),
        ("Refunded", "Refunded")
    ]

    posted_by = models.ForeignKey(
        "user.User", related_name="my_projects", null=True, on_delete=models.CASCADE)
    hired = models.ForeignKey("user.User", related_name="hired_projects",
                              null=True, on_delete=models.SET_NULL, blank=True)
    category = models.ForeignKey(
        "projects.ProjectCategory", null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=250)
    pricing_type = models.CharField(max_length=250, choices=pricing_types)
    detail = RichTextUploadingField(null=True, blank=True)
    status = models.CharField(
        max_length=250, choices=project_status, default="PEN", blank=True)
    price_status = models.CharField(
        max_length=250, choices=price_stats, default="NEGOTIATE")
    expires_on = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    start_date = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    end_date = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    start_time = models.TimeField(
        auto_now=False, auto_now_add=False, null=True, blank=True)
    end_time = models.TimeField(
        auto_now=False, auto_now_add=False, null=True, blank=True)
    posted_on = models.DateField(auto_now_add=True, blank=True, null=True)
    desired_skills = models.ManyToManyField(
        "projects.DesiredExpertise", blank=True)
    interviewing = models.ManyToManyField("user.User", blank=True)
    price = models.FloatField(null=True, blank=True)
    location = CountryField()
    address = models.CharField(max_length=50, null=True, blank=True)
    experience_needed = models.IntegerField(null=True, blank=True)
    can_apply = models.BooleanField(default=False)
    # if employer paid the the platform project price
    employer_payment_status = models.CharField(
        max_length=20, choices=deposit_status, blank=True, default="Unpaid")

    activities = GenericRelation("user.ActivityLog")
    notify = GenericRelation(Notification)
    objects = ProjectManager()

    def __str__(self) -> str:
        return self.title[:30]

    @property
    def get_skills(self):
        return self.desired_skills.all()

    @property
    def get_documents(self):
        return self.projectdocument_set.all()

    @property
    def get_skills_in_comma(self):
        return ','.join([i.skill_name for i in self.get_skills])

    @property
    def no_of_proposals(self):
        return self.proposals.count()

    @property
    def total_invites(self):
        return self.project_invites.count()

    @property
    def total_answered_invites(self):
        return self.project_invites.filter(answered=False).count()

    @property
    def no_of_interviewing(self):
        return self.interviewing.all().count()

    @property
    def has_hired(self):
        return True if self.hired else False

    @cached_property
    def hired_date(self):
        b = HiredModel.objects.get(project=self)
        return b.hired_date

    @property
    def get_expiry_days(self):
        today = date.today()
        l_date = self.expires_on
        delta = l_date - today
        return delta.days

    class Meta:
        ordering = ['-id']
        verbose_name_plural = "Projects"

    def get_absolute_url(self):
        return reverse('project_detail', kwargs={'id': int(self.id)})

    # based on uesr detail url is different

    def get_absolute_for_freelancer(self):
        return reverse('free_project_detail', kwargs={'id': int(self.id)})


class HiredModel(models.Model):
    """Model to track hire information"""
    project = models.ForeignKey(
        "projects.Project", related_name="project_hires", null=True, on_delete=models.CASCADE)
    hired_by = models.ForeignKey(
        "user.User", related_name="hired", null=True, on_delete=models.CASCADE)
    got_hired = models.ForeignKey(
        "user.User", related_name="got_hired", null=True, on_delete=models.SET_NULL)
    hired_date = models.DateField(auto_now_add=True)
    activities = GenericRelation("user.ActivityLog")
    notify = GenericRelation(Notification)


class InviteModel(models.Model):
    project = models.ForeignKey(
        "projects.Project", related_name="project_invites", null=True, on_delete=models.CASCADE)
    sent_by = models.ForeignKey(
        "user.User", related_name="invites_sent", null=True, on_delete=models.CASCADE)
    sent_to = models.ForeignKey(
        "user.User", related_name="invites_got", null=True, on_delete=models.SET_NULL)
    detail = models.TextField()
    answered = models.BooleanField(default=False)
    posted_on = models.DateField(auto_now_add=True)
    estimated_duration = models.CharField(max_length=100)
    estimated_price = models.FloatField()
    activities = GenericRelation("user.ActivityLog")
    accepted = models.BooleanField(null=True, blank=True)
    notify = GenericRelation(Notification)

    def __str__(self) -> str:
        return f'Invite from {self.sent_by} to {self.sent_to}'

    def get_absolute_url(self):
        return reverse('invite_list')

    def get_absolute_for_freelancer(self):
        return reverse('free_invite_list')

    def answer_invite(self, accepted, user):
        self.accepted = accepted
        self.answered = True
        self.save()
        answer = "accepted" if self.accepted else "rejected"
        self.notify.create(
            action_by=user,
            action_to=self.sent_by,
            action="hired",
            title=f"{self.sent_to} {answer} your invitation.",
        )
        if accepted:
            HiredModel.objects.create(
                project=self.project, hired_by=self.sent_by, got_hired=user)


class ProjectLinks(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    link = models.URLField(max_length=200)


class ProjectDocument(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    documents = models.FileField(upload_to='project_files')

    @cached_property
    def get_file_name(self):
        return self.documents.url.split("/")[-1]


class Proposal(models.Model):
    user = models.ForeignKey(
        "user.User", related_name="proposals", on_delete=models.CASCADE)
    project = models.ForeignKey(
        "projects.Project", related_name="proposals", on_delete=models.CASCADE)
    detail = models.TextField()
    price = models.FloatField()
    created_on = models.DateField(null=True, auto_now_add=True)
    activities = GenericRelation("user.ActivityLog")
    notify = GenericRelation(Notification)


class Reviews(models.Model):
    review_by = models.ForeignKey(
        "user.User", related_name="reviews_given", on_delete=models.CASCADE)
    review_to = models.ForeignKey(
        "user.User", related_name="reviews_got", on_delete=models.CASCADE)
    review = models.TextField()
    rating = models.IntegerField()
    for_project = models.ForeignKey(
        "projects.Project", on_delete=models.CASCADE)
    activities = GenericRelation("user.ActivityLog")
    notify = GenericRelation(Notification)
    is_approved = models.BooleanField(default=False)
    is_trash = models.BooleanField(default=False)

    class Meta:
        ordering = ["-id"]

    @property
    def rating_star(self):
        return list(range(0, self.rating))

    @property
    def rating_unstar(self):
        return list(range(0, 5-self.rating))

projects/templates/projects/freelancer/cancelled_projects.html
{% extends 'projects/freelancer/base_project.html' %}
{% load static %}
{% load extras %}
{% block title %}
Cancelled Projects
{% endblock title %}

{% block project %}
<!-- Page Content -->			  
<nav class="user-tabs mb-4">
                    <ul class="nav nav-tabs nav-tabs-bottom nav-justified">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'proposals' %}">My Proposals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'free_ongoing_projects' %}">Ongoing Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'free_completed_projects' %}">Completed Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'free_cancelled_projects' %}">Cancelled Projects</a>
                        </li>
                    </ul>
                </nav> 
                
     <!-- project list -->
     {% for list in page_obj %}
     <div class="my-projects-list">
         <div class="row">
             <div class="col-lg-12 flex-wrap">
                 <div class="projects-card flex-fill">
                     <div class="card-body">
                         <div class="projects-details align-items-center">
                             <div class="project-info project">
                                 <span>{{list.title}}</span>
                                 <h2>{{list.title}}</h2>
                                 <div class="proposal-client">
                                     <h4 class="title-info">Client Price</h4>
                                     <div class="d-flex">
                                         <h3 class="client-price me-2">${{list.price}}</h3>
                                         <p class="amnt-type">( {{list.get_pricing_type_display}} )</p>
                                     </div>
                                 </div>
                             </div>
                             <div class="project-hire-info project">
                                 <div class="content-divider"></div>
                                 <div class="proposer-info project">
                                     <div class="proposer-img">
                                         <img src="{{list.posted_by.avatar.url}}" alt="" class="img-fluid">
                                     </div>
                                     <div class="proposer-detail">
                                         <h4>{{list.posted_by.display_name}} </h4>
                                         <ul class="proposal-details">
                                             {% comment %} <li> October 26, 2022</li> {% endcomment %}
                                             <li>Rated 4 <i class="fas fa-star text-primary"></i> </li>
                                         </ul>
                                     </div>
                                 </div>
                                 <div class="content-divider"></div>
                                 <div class="projects-action text-start project">
                                     <a href="{% url 'free_project_detail' list.id %}" class="projects-btn project">View Details </a>
                                     <p class="hired-detail">Hired on</p>
                                     <p class="hired-date">{{list.hired_date}}</p>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>

     {% empty %}

                <h4 class="text-center">No Cancelled Projects !</h4>
                {% endfor %}
                <!-- /project list -->
                
               <!-- pagination -->
<div class="row">
    <div class="pagination mt-3">
        {% include 'components/pagination.html' %}
    </div>
      
</div>
<!-- /pagination -->
                
 
<!-- /Page Content -->
{% endblock project %}

projects/templates/projects/freelancer/completed_projects.html
{% extends 'projects/freelancer/base_project.html' %}
{% load static %}
{% load extras %}
{% block title %}
Completed Projects
{% endblock title %}

{% block project %}
<!-- Page Content -->			
                <nav class="user-tabs mb-4">
                    <ul class="nav nav-tabs nav-tabs-bottom nav-justified">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'proposals' %}">My Proposals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'free_ongoing_projects' %}">Ongoing Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'free_completed_projects' %}">Completed Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'free_cancelled_projects' %}">Cancelled Projects</a>
                        </li>
                    </ul>
                </nav> 
                <!-- project list -->
                {% for list in page_obj %}
                <div class="my-projects-list">
                    <div class="row">
                        <div class="col-lg-12 flex-wrap">
                            <div class="projects-card flex-fill">
                                <div class="card-body">
                                    <div class="projects-details align-items-center">
                                        <div class="project-info project">
                                            {% comment %} <span>{{list.title}}</span> {% endcomment %}
                                            <h2>{{list.title}}</h2>
                                            <div class="proposal-client">
                                                <h4 class="title-info">Client Price</h4>
                                                <div class="d-flex">
                                                    <h3 class="client-price me-2">${{list.price}}</h3>
                                                    <p class="amnt-type">( {{list.get_pricing_type_display}} )</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="project-hire-info project">
                                            <div class="content-divider"></div>
                                            <div class="proposer-info project">
                                                <div class="proposer-img">
                                                    <img src="{{list.posted_by.avatar.url}}" alt="" class="img-fluid">
                                                </div>
                                                <div class="proposer-detail">
                                                    <h4>{{list.posted_by.display_name}} </h4>
                                                    <ul class="proposal-details">
                                                        {% comment %} <li> October 26, 2022</li> {% endcomment %}
                                                        <li>Rated 4 <i class="fas fa-star text-primary"></i> </li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="content-divider"></div>
                                            <div class="projects-action text-start project">
                                                <a href="{% url 'free_project_detail' list.id %}" class="projects-btn project">View Details </a>
                                                <p class="hired-detail">Hired on</p>
                                                <p class="hired-date">{{list.hired_date}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {% empty %}

                <h4 class="text-center">No Completed Projects !</h4>
                {% endfor %}
                <!-- /project list -->
                
               <!-- pagination -->
            <div class="row">
                <div class="pagination mt-3">
                    {% include 'components/pagination.html' %}
                </div>
                
            </div>
            <!-- /pagination -->
                
 
<!-- /Page Content -->
{% endblock project %}

projects/templates/projects/freelancer/ongoing_projects.html
{% extends 'projects/freelancer/base_project.html' %}
{% load static %}
{% load extras %}
{% block title %}
Ongoing Projects
{% endblock title %}

{% block project %}
            <!-- Page Content -->			
            <nav class="user-tabs mb-4">
                <ul class="nav nav-tabs nav-tabs-bottom nav-justified">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'proposals' %}">My Proposals</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'free_ongoing_projects' %}">Ongoing Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'free_completed_projects' %}">Completed Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'free_cancelled_projects' %}">Cancelled Projects</a>
                    </li>
                </ul>
            </nav> 
                <!-- project list -->
                {% for list in page_obj %}
                <div class="my-projects-list">
                    <div class="row">
                        <div class="col-lg-12 flex-wrap">
                            <div class="projects-card flex-fill">
                                <div class="card-body">
                                    <div class="projects-details align-items-center">
                                        <div class="project-info project">
                                            {% comment %} <span>{{list.title}}</span> {% endcomment %}
                                            <h2>{{list.title}}</h2>
                                            <div class="proposal-client">
                                                <h4 class="title-info">Client Price</h4>
                                                <div class="d-flex">
                                                    <h3 class="client-price me-2">${{list.price}}</h3>
                                                    <p class="amnt-type">( {{list.get_pricing_type_display}} )</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="project-hire-info project">
                                            <div class="content-divider"></div>
                                            <div class="proposer-info project">
                                                <div class="proposer-img">
                                                    <img src="{{list.posted_by.avatar.url}}" alt="" class="img-fluid">
                                                </div>
                                                <div class="proposer-detail">
                                                    <h4>{{list.posted_by.display_name}} </h4>
                                                    <ul class="proposal-details">
                                                        {% comment %} <li> October 26, 2022</li> {% endcomment %}
                                                        <li>Rated 4 <i class="fas fa-star text-primary"></i> </li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="content-divider"></div>
                                            <div class="projects-action text-start project">
                                                <a href="{% url 'free_project_detail' list.id %}" class="projects-btn project">View Details </a>
                                                <p class="hired-detail">Hired on</p>
                                                <p class="hired-date">{{list.hired_date}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {% empty %}

                <h4 class="text-center">No Ongoing Projects !</h4>
                
                {% endfor %}
                <!-- /project list -->
                
                <!-- pagination -->
                            <!-- pagination -->
                <div class="row">
                        <div class="pagination mt-3">
                            {% include 'components/pagination.html' %}
                        </div>
                        
                    </div>
                <!-- /pagination -->
                
 
<!-- /Page Content -->
{% endblock project %}