blog/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('blog-list', BlogListView.as_view(), name='blog_list_page'),
    path('blog-grid', BlogGridView.as_view(), name='blog_grid_page'),
    path('blog-detail/<str:slug>/', BlogDetailView.as_view(), name='blog_detail'),
]

mainproject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)
from .views import IndexView, SubscribeView
from .oauth import FacebookLogin, GoogleLogin
from user.api.urls import MyTokenObtainPairView


schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="batuwa@email.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('main/', admin.site.urls),

    #  path('', RedirectView.as_view(pattern_name='dashboard'),name='redirect'),
    #  path('', RedirectView.as_view(pattern_name='dashboard'),name='redirect'),
    path('', IndexView.as_view(), name='index'),
    path('dashboard/', RedirectView.as_view(pattern_name='dashboard'), name='redirect'),
    path('user/', include('user.urls')),
    path('project/', include('projects.urls')),
    path('membership/', include('membership.urls')),
    path('site/', include('sitesettings.urls')),
    path('admin/', include('user.admin_urls')),
    path('notice/', include('notification.urls')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls')),
    path('payments/', include('payments.urls')),
    path('blog/', include('blog.urls')),
    path('subscribe', SubscribeView.as_view(), name='subscribe'),

    # path('jwt/create/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('jwt/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('jwt/verify/', TokenVerifyView.as_view(), name='token_verify'),


    path('api/projects/', include('projects.api.urls')),
    path('api/user/', include('user.api.urls')),
    path('api/payments/', include('payments.api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="user/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    path('oauth/facebook/', FacebookLogin.as_view(), name='facebook_oauth'),
    path('oauth/google/', GoogleLogin.as_view(), name='google_oauth'),
    # path('dj-rest-auth/', include('dj_rest_auth.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns += [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger',
                                               cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc',
                                             cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/api/urls.py
from django.urls import path,include
from .views import *
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'fees', FeeViewset, basename='fees')
router.register(r'taxes', TaxViewset, basename='taxes')


urlpatterns  = [
    path('',include(router.urls)),
]

payments/urls.py
from django.urls import path

from .view.admin_view import *
from .view.employer_view import *
from .view.freelancer_view import *
from .view.webhook_view import my_webhook_view

freelancer_urls = [
   path('',FreelancerPayment.as_view(), name='freelancer_payment'),
   path('my-transaction/',FreelancerTranscation.as_view(), name='freelancer_transaction'),
   path('my-invoices/',FreelancerInvoices.as_view(), name='freelancer_invoices'),
   path('connect-account/',OnBoardUser, name='connect_account'),
   path('withdraw-money/',WithdrawMoney.as_view(), name='withdraw_money'),
   path('webhook-stripe/',my_webhook_view ,name="webhook"),  
]


employer_urls = [
   path('project-payment/<int:id>/',ProjectPaymentPage.as_view() , name="project_payment"),
   path('project-payment-intent/',ProjectPaymentIntentAPI.as_view() , name="project_payment_intent")
]


admin_urls =[
      path('transactions/',TransactionPage.as_view() , name="transactions"),
      path('deposits/',DepositPage.as_view() , name="deposits"),
      path('fee-list/',FeePage.as_view() , name="fee_list"),
      path('tax-list/',TaxPage.as_view() , name="tax_list"),
      path('release-money/',ReleaseMoneyAPI.as_view() , name="release_money"),
      path('refund-money/',RefundMoneyAPI.as_view() , name="refund_money"),

]

urlpatterns =freelancer_urls+employer_urls+admin_urls

user/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator
from notification.models import Notification
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from dateutil import relativedelta
from django_countries.fields import CountryField
from django.db.models.aggregates import Sum
from django.utils.functional import cached_property


class ActivityLog(models.Model):
    action = models.CharField(max_length=100)
    action_date = models.DateTimeField(auto_now_add=True)
    action_by = models.ForeignKey(
        "user.User", on_delete=models.CASCADE, related_name='activities')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()
    detail = models.CharField(max_length=100, null=True, blank=True)

    @property
    def get_description(self):
        if self.detail:
            return self.detail
        return f'{self.action_by} {self.action}  {self.content_object.__class__.__name__}'

    class Meta:
        ordering = ['-id']


class CustomUserManager(BaseUserManager):

    def create_user(self, email, username, password, **extra_fields):
        """
          Create and save a SuperUser with the given email,username, password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        if not username:
            raise ValueError(_('Username must be set'))
        if not password:
            raise ValueError(_('Password must be set'))

        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, password, **extra_fields):
        """
        Create and save a SuperUser with the given email,username, password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        b = self.create_user(email, username, password, **extra_fields)
        b.role = "Admin"
        b.save()
        return b


class User(AbstractUser):
    """
        Main User Model which has basic information
    """

    # using employer and freelancer since it is easy to understand the role
    # rather than batuwa or traveller (sounds same)
    # we will use employer or freelancer behind the scene
    # but show batuwa and traveller in front side
    role = [
        ('Admin', 'Admin'),
        ('Employer', 'Employer'),  # someone who post projects and hire freelancer
        # someone who take project by sending propposal
        ('Freelancer', 'Freelancer'),
    ]

    gender_types = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others'),
        ('Not Specify', 'Not Specify'),
    ]

    role = models.CharField(max_length=200, choices=role)
    email = models.CharField(max_length=200, unique=True)
    username = models.CharField(max_length=200, unique=True)
    display_name = models.CharField(max_length=200, null=True, blank=True)
    overview = models.TextField(blank=True, null=True)
    avatar = models.ImageField(default='default.png', upload_to='avatars')
    banner_image = models.ImageField(default='banner.jpg', upload_to='avatars')
    gender = models.CharField(
        max_length=100, choices=gender_types, default='Male')
    language_one = models.CharField(max_length=100, null=True, blank=True)
    title = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=150, null=True, blank=True)
    state = models.CharField(max_length=150, null=True, blank=True)
    country = CountryField(default='AF')
    zipcode = models.IntegerField(null=True, blank=True)
    contact = models.CharField(max_length=15, null=True, blank=True)
    hourly_rate = models.FloatField(null=True, blank=True, default=5)
    skills = models.ManyToManyField("projects.DesiredExpertise", blank=True)
    bookmarked_projects = models.ManyToManyField(
        "projects.Project", related_name="bookmared_projects")
    bookmarked_people = models.ManyToManyField("self")
    verified = models.BooleanField(default=False)
    user_ratings = models.FloatField(null=True, blank=True)
    user_ratings_floor = models.FloatField(null=True, blank=True)

    availability = models.BooleanField(default=False)
    activities = GenericRelation(ActivityLog)
    notify = GenericRelation(Notification)

    # freelancer rating based on completed projects rating by client

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        ordering = ['-date_joined']
        verbose_name_plural = "Custom Users"

    def __str__(self):
        return f'{self.username}'

    @cached_property
    def get_rating(self):
        count = self.reviews_got.count()
        if self.role != "Freelancer" or count < 1:
            return None
        total_rate = self.reviews_got.aggregate(sum=Sum("rating"))
        return total_rate["sum"]/count

    @cached_property
    def get_rating_floor(self):
        from math import floor
        if not self.get_rating:
            return None
        return floor(self.get_rating)

    @property
    def no_of_reviews_got(self):
        return self.reviews_got.count()

    @property
    def get_skills(self):
        return self.skills.all()

    @property
    def get_awards(self):
        return self.awards.all()

    @property
    def get_langs(self):
        return self.many_languages.all()

    @property
    def get_bookmarked_projects(self):
        return self.bookmarked_projects.all()

    @property
    def get_bookmarked_users(self):
        return self.bookmarked_people.all()

    @property
    def get_project_posted(self):
        return self.my_projects.count()

    @property
    def get_project_hired(self):
        return self.hired.count()

    @property
    def get_open_job(self):
        return self.my_projects.filter(can_apply=True, expires_on__gte=datetime.today()).count()

    @property
    def get_finished_jobs(self):
        return self.hired_projects.filter(status="COM").count()

    @property
    def get_hired_rate(self):
        if self.get_project_hired == 0:
            return 0
        return (self.get_project_hired/self.get_project_posted)*100

    @property
    def profile_complete_percentage(self):
        count = 0
        if self.is_active:
            count += 1

        if self.email:
            count += 1

        if self.username:
            count += 1

        if self.display_name:
            count += 1

        if self.avatar:
            count += 1

        if self.overview:
            count += 1

        if self.gender:
            count += 1

        if self.address:
            count += 1

        if self.country:
            count += 1

        if self.contact:
            count += 1

        if self.hourly_rate:
            count += 1

        if self.skills:
            count += 1

        if self.zipcode:
            count += 1

        if self.verified:
            count += 1

        if self.title:
            count += 1

        percent = count/15 * 100

        return int(percent)

    @property
    def total_payment(self):
        total_payment = 0
        for i in self.my_deposits.filter(transaction__types='Transfer', transaction__status='success'):
            total_payment += i.transaction.price
        return total_payment

    @property
    def follower_count(self):
        return self.user_follow_to.all().count()

    @property
    def following_count(self):
        return self.user_follow_by.all().count()

    @property
    def active_proposal(self):
        count = 0
        for i in self.proposals.all():
            if i.project.status == 'Active':
                count += 1
        return count

    @property
    def applied_proposal(self):
        return self.proposals.all().count()

    @property
    def hired_jobs(self):
        return self.hired.all().count()


class WeekDayAvailable(models.Model):
    """
        This gives the weekly availabilty of freelancer
        Eg: Sunday (1am to 5pm)
            Monday (2am to 6am)
    """
    weekday = [
        ('Sunday', 'Sunday'),
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),

    ]
    name = models.CharField(max_length=10, choices=weekday)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    available_from = models.TimeField(
        auto_now=False, auto_now_add=False, null=True, blank=True)
    available_to = models.TimeField(
        auto_now=False, auto_now_add=False, null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.name} {self.id}"


class Languages(models.Model):
    user = models.ForeignKey(
        "user.User", related_name="many_languages", on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=150)
    fluency = models.PositiveSmallIntegerField(default=50, validators=[
        MaxValueValidator(100),
        MinValueValidator(1)
    ]
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Languages"

payments/api/views.py
from rest_framework import exceptions, status,viewsets
from rest_framework.permissions import  IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from ..models import FeeModel,TransactionModel,TaxModel
from .serializers import *
from django_filters.rest_framework import DjangoFilterBackend
from mainproject.pagination import CustomPagination
from user.api.permissions import IsBatuwaAdminOnly

class FeeViewset(viewsets.ModelViewSet):
    queryset = FeeModel.objects.all()
    serializer_class = FeeSerializer
    filter_backends = (DjangoFilterBackend,)
    pagination_class = CustomPagination
    permission_classes  =[IsBatuwaAdminOnly]
    search_fields = ("name",)

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        pk = instance.id
        self.perform_destroy(instance)
        return Response( {'type':'delete','id':pk}, status=status.HTTP_200_OK)

class TaxViewset(viewsets.ModelViewSet):
    queryset = TaxModel.objects.all()
    serializer_class = TaxSerializer
    permission_classes  =[IsBatuwaAdminOnly]
    filter_backends = (DjangoFilterBackend,)
    pagination_class = CustomPagination
    search_fields = ("name",)

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        pk = instance.id
        self.perform_destroy(instance)
        return Response( {'type':'delete','id':pk}, status=status.HTTP_200_OK)

class TransactionViewset(viewsets.ReadOnlyModelViewSet):
    queryset = TransactionModel.objects.all()
    serializer_class = TransactionSerializer
    filter_backends = (DjangoFilterBackend,)
    pagination_class = CustomPagination
    search_fields = ("name",)
    permission_classes=[IsAuthenticated]

payments/templates/payments/admin/transaction_list.html
{% extends 'admin/adminbase.html' %}
{% load static %}
{% load extras %}
{% load crispy_forms_tags %}

{% block title %}Transaction List{% endblock title %}
{% block content %}

<div class="page-wrapper">
    <div class="content container-fluid">
    
        <!-- Page Header -->
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Transactions List</h3>
                    {% comment %} <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                        
                        <li class="breadcrumb-item active">Users</li>
                    </ul> {% endcomment %}
                </div>
                <div class="col-auto">
                    <a href="#" class="btn add-button me-2" data-bs-toggle="modal" data-bs-target="#add-category">
                        <i class="fas fa-plus"></i>
                    </a>
                    <a class="btn filter-btn" href="javascript:void(0);" id="filter_search">
                        <i class="fas fa-filter"></i>
                    </a>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        {% include 'components/message.html' %}


        <!-- Search Filter -->
        <div class="card filter-card" id="filter_inputs">
            <div class="card-body pb-0">
                <form method="get" style="display:flex;flex-wrap:wrap;gap:1rem;align-items:center;" class="">
                    {{searchForm.form|crispy}}
                    <button type="submit" class="btn btn-primary mb-4">Search</button>
              </form> 
            </div>
        </div>
        <!-- /Search Filter -->

        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-center table-hover mb-0 ">
                                <thead>
                                    <tr>
                                        <th> Id</th>
                                        <th>Transaction By</th>
                                        <th>Type</th>	
                                        <th>Status</th>	
                                        <th>Amount</th>
                                        <th>Date Created</th>	
                                        <th class="text-end"></th>
                                    </tr>
                                </thead>
                                <tbody id="tablediv">
                               {% for list in page_obj %}
                                    <tr id="user-{{list.id}}">
                                        <td>
                                              {{list.id}}
                                        </td>
                                        <td>
                                            <h2 class="table-avatar">
                                                <a href="{% url 'admin_user_detail' list.transaction_by.id %}"><img class="me-2 rounded-circle object-cover" src="{{list.transaction_by.avatar.url}}"  alt="User Image">{{list.transaction_by.display_name}}</a>
                                            </h2>
                                        </td>
                                        <td>{{list.type}}</td>
                                        <td>
                                             {{list.status}}
                                        </td>
                                        <td>
                                        ${{list.price}}
                                        </td>
                                      
                                        <td>{{list.created_at}}</td>
                                        <td class="text-end">

                                            {% comment %} <a href="javascript:void(0);" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#delete_user_{{list.id}}"><i class="far fa-trash-alt"></i></a> {% endcomment %}
                                        </td>
                                    </tr>

                                    <!-- Delete Modal -->
                                    {% comment %} <div class="modal custom-modal fade" id="delete_user_{{list.id}}" role="dialog">
                                        <div class="modal-dialog modal-dialog-centered">
                                            <div class="modal-content">
                                                <div class="modal-body">
                                                    <div class="form-header">
                                                        <h3>Delete</h3>
                                                        <p>Are you sure want to delete?</p>
                                                    </div>
                                                    <div class="modal-btn delete-action">
                                                        <form method="POST"  hx-post="{% url 'user_list' %}" hx-trigger="submit" hx-swap="none" >
                                                           
                                                            <div class="row">
                                                                <div class="col-6">
                                                                    <input type="hidden" name="u_id" value="{{list.id}}"/>
                                                                    <input type="hidden" name="delete_user" value="{{list.id}}"/>
                                                                    <input type="submit" name="delete_user" class="btn btn-primary continue-btn w-100" value="Delete" />
                                                                </div>
                                                                <div class="col-6">
                                                                    <a href="javascript:void(0);" data-bs-dismiss="modal" class="btn btn-primary cancel-btn">Cancel</a>
                                                                </div>
                                                            </div>

                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div> {% endcomment %}
                                    <!-- /Delete Modal -->
                                    {% empty %}
                                    <tr><td>Not Found Any User</td></tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>			
        </div>
        <div class="float-right mt-3">
            {% include 'components/pagination.html' %}
        </div>
          
    </div>			
</div>
{% endblock content %}